### ISSUE TITLE
AH money glitch.

### ISSUE THREAD

**Issue by Mischa-Lamoureux** [OfficialLexplex/survival#7]
When someone buys something from you off of AH (Auction House) it gives negative money. For example: I put 64 dirt on AH for $500. Someone bought it and it said: [Name] purchased your auction and you earned $-1500. I didn't earn any money nor did it take money away from me. My balance stayed the same. Please try to fix this glitch ASAP as people can basically rob you.

**Comment by mecray** [comment]
Thanks for letting me know. We will temporarily disable auction house until this is sorted.

**Comment by mecray** [comment]
Thank you! The issue has been resolved.
